[package]
name = "jwks_registry"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/aztec" }
att_verifier_lib = { path = "../../../lib/att_verifier_lib" }
